name = "wispy-resonance-6b301" # todo!
main = "./src/index.ts"
compatibility_date = "2023-03-30"

# wrangler.toml
[observability]
enabled = false

[env.staging]
vars = { ENVIRONMENT = "staging" }

[env.production]
vars = { ENVIRONMENT = "production" }
